### ISSUE TITLE
update needed to keep compliance with parse-server

### ISSUE THREAD

**Issue by flovilmart** [Kira2/parse-server-mailjet-adapter#1]
Starting that PR: https://github.com/ParsePlatform/parse-server/pull/2732 user.get('email') may be undefined for all calls but `sendMail`.

You should be prepared to use `user.get('username')` if `user.get('email')` is not set.

**Comment by Kira2** [comment]
@flovilmart Thanks for the update. I'll take a look and make the needed changes.
